#!/bin/sh
# Example of hooks/post-receive file of a Git repository.

# Change this if you want to use another ircpipe program
IRCPIPE="/usr/share/kaoz-clients/shell/ircpipe.sh"

/usr/share/kaoz-clients/git/send-message
