#!/bin/sh
# Format Git commits in colors with IRC
# Usage:
#  echo oldrev newrev refname | git/send-message
# Example:
#  echo 012345 abcdef master | git/send-message

source "${KAOZ_CLIENTS_PATH:-/usr/share/kaoz-clients}/shell/irc-style.sh"

read OLDREV NEWREV REFNAME

BRANCH=$(echo -n "$REFNAME" | sed 's-.*/^\([^/]*\)-\1-')

GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
DESC_FILE="$GIT_DIR/description"
if [ -r "$DESC_FILE" ]
then
    DESCRIPTION=$(sed -ne '1p' "$DESC_FILE")
else
    DESCRIPTION=$(basename "$GIT_DIR")
fi

IRC_CHANNEL=$(git config hooks.ircchannel)

# Execute git log
DESCRIPTION="${IRC_GREEN}[${DESCRIPTION}:${BRANCH}]${IRC_O}"
AUTHOR="${IRC_RED}%an${IRC_O}"
HASH="${IRC_NAVY}%h${IRC_O}"
(
git log --pretty="format:$DESCRIPTION $AUTHOR $HASH %s" "$OLDREV..$NEWRED"
echo ""
) | ${IRCPIPE:-/usr/share/kaoz-clients/shell/ircpipe.sh} "$IRC_CHANNEL"
