#!/bin/sh
# You may copy this file and modify it to get it fit our own configuration.

IRCPIPE="${KAOZ_CLIENTS_PATH:-/usr/share/kaoz-clients}/pipes/ircpipe.sh"
CHANNEL="" # Empty for default channel

"${KAOZ_CLIENTS_PATH:-/usr/share/kaoz-clients}/pam/format-message" | $IRCPIPE $CHANNEL
